# test for HPC 
# ansible playbook for HPC cluster deployment


- name: config ssh passwordless login
  hosts: all
  tasks:
    - name: create a ssh_hosts file including all manager and compute nodes
      shell: echo hostvars[inventory_hostname] >> /tmp/test


- name: install OpenPBS on manager node
  hosts: manager
  tasks:



- name: install openPBS on compute node
  hosts: compute
  tasks:
 
