# install openmpi

- name: install and config openmpi
  hosts: all
  tasks:
    - name: install openmpi packages
      yum:
        name: openmpi
        state: present

    - name: add path to env
      lineinfile: 
        path: /etc/profile
        line: export PATH=$PATH:/usr/lib64/openmpi/bin


